### ISSUE TITLE
Ringcentral synchronizing with leads in insightly

### ISSUE THREAD

**Issue by AtanasGodman** [ringcentral/insightly-embeddable-ringcentral-phone#36]
Greetings,

Thank you for creating this extension. It does an awesome job and it is an integral part of our day to day use of Insightly.

However we encountered and issue which we are trying to resolve and are coming back to you for help.

We have thousands of people on our Insightly registered as leads and not as Contacts. We can call them with the RC extension but RC does not record the inbound and outbound calls in Insightly.

From the videos I can see that it does that with Contacts. 

So, I am asking of you can advise me on how to do that with Leads. Or you can add that option in the next version.

Please let me know.

Thank you for your help and great work.

Kind regards,
Atanas

**Comment by zxdong262** [comment]
@AtanasGodman Hi, I will investigate this, I never used leads before. Thank you for the feedback.

**Comment by zxdong262** [comment]
@AtanasGodman Sorry for the delay, now it supports leads now, you could download the latest edition.
