### ISSUE TITLE
Unable to run CRM

### ISSUE THREAD

**Issue by jmlugares** [ringcentral/insightly-embeddable-ringcentral-phone#37]
Hello Team, 

We are having an issue with integrating RingCentral to Insistingly after running the steps recommended. After installing 0.4.7 via google extension we got the following window (please refer to screenshot) and unable to run the app 

In addition we tried logging to the link https://crm.*.insightly.com  and got the following message site cannot be reached

Looking forward for your update

Thank you 
![Capture](https://user-images.githubusercontent.com/52936394/61556744-2179f300-aa95-11e9-9aeb-03c1b9ef965f.JPG)

**Comment by zxdong262** [comment]
Sorry, missed the message, submit a new release with insight.ly support, please try this, let know if have any problems.

https://github.com/ringcentral/insightly-embeddable-ringcentral-phone/releases/tag/v0.4.8
