### ISSUE TITLE
Activity log not updating, screen pop not triggering

### ISSUE THREAD

**Issue by doberusa** [ringcentral/insightly-embeddable-ringcentral-phone#46]
Setup the extension today to use for a team that has RC Office so that they can use Insightly as their CRM. Extension installed fine, web hook registers, can call from Insightly, but activity not being logged. More importantly, the screen pop with the callers information is not happening (which is key). Looks great though! Please let me know if there is a solution.

**Comment by zxdong262** [comment]
@doberusa Thank you for the feedback

I will check it, if there is a problem, I will fix it and let you know.

**Comment by doberusa** [comment]
Thank you.

**Comment by zxdong262** [comment]
https://github.com/ringcentral/insightly-embeddable-ringcentral-phone/releases/tag/v2.0.0

@doberusa New version released, you may try it.
