### ISSUE TITLE
Insightly Styling altered by latest version 2.0.0

### ISSUE THREAD

**Issue by ctanner88** [ringcentral/insightly-embeddable-ringcentral-phone#48]
Hi there,

I installed the latest version of the Insightly Chrome Extension this morning and realized it was altering the styling across Insightly. Please see the screenshots.

![image (10)](https://user-images.githubusercontent.com/70219335/91586317-cca4df00-e91a-11ea-9ade-22ce7333fccb.png)
This is Insightly's default styling with the extension disabled.

![image (11)](https://user-images.githubusercontent.com/70219335/91586323-ce6ea280-e91a-11ea-8cab-db9aa3dc6d64.png)
This is after enabling the extension and refreshing the page.

Windows 10, Chrome v. 85.0.4183.83

**Comment by zxdong262** [comment]
Fixed in latest release, thank you for the feedback! @ctanner88 
https://github.com/ringcentral/insightly-embeddable-ringcentral-phone/releases/tag/v2.1.1
