### ISSUE TITLE
Insightly Tab - Recent Records Not Working

### ISSUE THREAD

**Issue by ctanner88** [ringcentral/insightly-embeddable-ringcentral-phone#49]
When I click into a Contact's details page, the Insightly tab does not provide any information for any Contact we have. The Call Log and SMS Log work as expected. Please see the following screenshots:

![norecords](https://user-images.githubusercontent.com/70219335/93117587-af933e80-f684-11ea-9411-dc0e1afb27ad.PNG)
![contact calls](https://user-images.githubusercontent.com/70219335/93117578-ac984e00-f684-11ea-92fe-a0f4fd189376.PNG)

Can you also verify which activities or records are supposed to show in this tab? I checked the documentation but it does not specify which activities or records should be here. I've tested with a variety of records within Insightly (opportunity, task, event) and none have shown up in that tab.

**Comment by zxdong262** [comment]
Fixed in new release: https://github.com/ringcentral/insightly-embeddable-ringcentral-phone/releases/tag/v2.2.0

Thank you for the feedback!
