### ISSUE TITLE
RingCentral / Insightly Integration Issue

### ISSUE THREAD

**Issue by MeganVSattui** [ringcentral/insightly-embeddable-ringcentral-phone#50]
Hi Drake!

I'm working with Jose in the RingCentral integrations team. We've verified that the plug in for insightly is not efficient due to the requirement of syncing records daily due to our very large database. (about 40K). We understand you have a built-in for HubSpot we hope this can be implemented for insightly as well. I know other users of the platform would benefit greatly. 

We need a built in widget that tracks all call/text activity to each record in our organization without having to sync contacts with every login. 

This is urgent for us. We actually hope to have this within the month. Is it possible?

Thanks!

**Comment by zxdong262** [comment]
It is the same code base with HubSpot chrome extension, in HubSpot if user add new contacts, they need sync the contacts data too.

It do not require to sync all contacts at every login, if no new contacts added, you do not need to resync conatcts, if you only add new contacts, you can choose sync recent added contacts, it will be much faster.

Make sure you are using the latest release, which is 2.2.0 currently: https://github.com/ringcentral/insightly-embeddable-ringcentral-phone/releases/tag/v2.2.0.

Let me know if you still have problems using it.

**Comment by MeganVSattui** [comment]
Hey Drake!

That has definitely not been the experience. Our plug in does not seem to work without syncing.

@Tech Support<mailto:techsupport@ringcentral.com>, can you please advise? Is there something that is not correctly set up on our end?

Megan Furth | Outbound Hospitality & Marketing Manager
[vsattui_wordmark+shadow_blk_cmyk]
1111 White Lane St. Helena, CA 94574
(707) 286-7212 Direct | (707) 363-9003 Mobile
(707) 963-7774 Winery Office (Open 9-5, Mon–Fri)
megan@vsattui.com<http://www.vsattui.com/>
www.vsattui.com<http://www.vsattui.com/>

**Comment by zxdong262** [comment]
@MeganVSattui Can we have a meeting to check it?

**Comment by MeganVSattui** [comment]
Definitely! Tomorrow? What time?

Megan Furth | Outbound Hospitality & Marketing Manager
[vsattui_wordmark+shadow_blk_cmyk]
1111 White Lane St. Helena, CA 94574
(707) 286-7212 Direct | (707) 363-9003 Mobile
(707) 963-7774 Winery Office (Open 9-5, Mon–Fri)
megan@vsattui.com<http://www.vsattui.com/>
www.vsattui.com<http://www.vsattui.com/>

**Comment by zxdong262** [comment]
@MeganVSattui 

I had a meeting with another user who reported same isuue, I know it now.
This is the new release: https://github.com/ringcentral/insightly-embeddable-ringcentral-phone/releases/tag/v2.2.2
Thank you for the feedback, for the first time use, you may still need to finish a full resync, then it will not resync on every refresh.

**Comment by MeganVSattui** [comment]
Thank you! We will try this and see if it solves the issue.

Best,
Megan

Megan Furth | Outbound Hospitality & Marketing Manager
[vsattui_wordmark+shadow_blk_cmyk]
1111 White Lane St. Helena, CA 94574
(707) 286-7212 Direct | (707) 363-9003 Mobile
(707) 963-7774 Winery Office (Open 9-5, Mon–Fri)
megan@vsattui.com<http://www.vsattui.com/>
www.vsattui.com<http://www.vsattui.com/>
